Android 11 device controls
openhab/openhab-android pull request #2738
Opened 2021-10-27 16:44 UTC by wiomoc

Implements basic functionality for controlling items over the [device control API](https://developer.android.com/guide/topics/ui/device-control#kotlin) released in Android 11

closes #2210

2021-10-30 12:43 UTC, mueller-ma commented
I tested this with the demo server and have a few questions/suggestions:

- [ ] Item `RGBLight` does always show `0%` when the light is `ON`.
- [ ] Do you want to add support for more item types in this PR?
- [ ] When long pressing a control it always only opens MainActivity, but I'm not sure if there's another practical solution. Maybe ensure it opens the primary server at least? Look for `EXTRA_SERVER_ID` in `MainActivity`.
- [ ] Can you pick https://github.com/openhab/openhab-android/commit/cdd8aab1f7d0d3c5dfe5a0cb8be2dab889d876e2?
- [ ] The lint issue `Missing PendingIntent mutability flag` is showing up in line 237.

2021-10-30 19:04 UTC, wiomoc commented
I have taken into account all your suggestions in the last commit. I have also added support for the number type. Now I don't want to add more types 😉

2021-10-31 09:23 UTC, mueller-ma requested changes
I see the following line multiple times in the log:

> W/ControlsProviderService: onNext(): control is not stateless. Use the Control.StatelessBuilder() to build the control.

When `createPublisherForAllAvailable()` is called, it should use `Control.StatelessBuilder()`: https://developer.android.com/guide/topics/ui/device-control

2021-10-31 09:23 UTC, mueller-ma commented on mobile/src/main/java/org/openhab/habdroid/model/Item.kt
> +    fun JSONObject.getDoubleOrNull(name: String) = if (has(name)) {
This function should be placed next to `JSONObject.optStringOrNull()` and be renamend to `JSONObject.optDoubleOrNull`.

2021-10-31 09:23 UTC, mueller-ma commented on mobile/src/main/java/org/openhab/habdroid/model/Item.kt
> +        step
I'd parse the json here, no need for these variables.

2021-10-31 09:23 UTC, mueller-ma commented on mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
> +        item.name, item.minimum?.toFloat() ?: 0F, item.maximum?.toFloat() ?: 100F,
`Number` items may have a larger value than 100, but no `maximum` defined, e.g. `AlarmSystem_PinCode` on the demo server:
````
AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: org.openhab.habdroid, PID: 6132
    java.lang.IllegalArgumentException: currentValue=1234.000000 > maxValue=100.000000
        at android.service.controls.templates.RangeTemplate.validate(RangeTemplate.java:181)
        at android.service.controls.templates.RangeTemplate.<init>(RangeTemplate.java:83)
        at org.openhab.habdroid.background.ItemsControlsProviderService.createRangeTemplate(ItemsControlsProviderService.kt:182)
        at org.openhab.habdroid.background.ItemsControlsProviderService.maybeCreateStatefulControl(ItemsControlsProviderService.kt:203)
        at org.openhab.habdroid.background.ItemsControlsProviderService.access$maybeCreateStatefulControl(ItemsControlsProviderService.kt:55)
        at org.openhab.habdroid.background.ItemsControlsProviderService$createPublisherForAllAvailable$job$1.invokeSuspend(ItemsControlsProviderService.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
````

2021-10-31 12:02 UTC, mueller-ma commented on mobile/src/main/java/org/openhab/habdroid/background/ItemsControlsProviderService.kt
> +                Item.Type.Switch, Item.Type.Dimmer, Item.Type.Color, Item.Type.Rollershutter, Item.Type.Number ->
This list of valid item types has to be maintained here and in the assignment of `controlTemplate` above. I'd assign `controlTemplate` unconditionally and keep the `return null` for unsupported item types there.
Then this list of types can be removed here.

2021-10-31 14:47 UTC, merged

2021-10-31 14:47 UTC, mueller-ma commented
Thanks!