assets/store_descriptions/en-US/strings.xml: add fullstop at end of sentences
openhab/openhab-android pull request #3645
Opened 2024-04-14 17:24 UTC by dilyanpalauzov

Closes https://github.com/openhab/openhab-android/issues/3631

2024-04-16 19:04 UTC, mueller-ma requested changes
Please sign-off your commits with `git commit -s`

2024-04-16 19:04 UTC, mueller-ma commented on assets/store_descriptions/en-US/strings.xml
> +    <bindings>Over 200 specific add-ons provide support for brands, devices, technologies and communication protocols. Examples are Z-Wave, Philips Hue, Amazon Echo, Chromecast and Sonos. Discover al
I'd omit the full stop here...

2024-04-16 19:04 UTC, mueller-ma commented on assets/store_descriptions/en-US/strings.xml
> +    <fdroid_privacy_policy>Privacy policy: https://www.openhabfoundation.org/privacy.html#android-app.</fdroid_privacy_policy>
... and here

2024-04-17 05:06 UTC, dilyanpalauzov commented on assets/store_descriptions/en-US/strings.xml
> +    <bindings>Over 200 specific add-ons provide support for brands, devices, technologies and communication protocols. Examples are Z-Wave, Philips Hue, Amazon Echo, Chromecast and Sonos. Discover al
> Please sign-off your commits with `git commit -s`

This is irrelevant.

2024-04-18 05:43 UTC, merged